---
title: "Results"
output: word_document
# output: rmarkdown::html_vignette
# vignette: >
#   %\VignetteIndexEntry{run_simulation}
#   %\VignetteEngine{knitr::rmarkdown}
#   %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  comment = "#>"
)
# library(vax.eff)
devtools::load_all()
library(tidyverse)
library(magrittr)
library(pander)
library(xtable)
library(purrr)
library(ggplot2)
library(tibble)
library(latex2exp)
library(janitor)
library(scales)

panderOptions('table.split.table', Inf)
panderOptions("keep.trailing.zeros", TRUE)
```

## Figure 1

```{r}
R = 0.2
pV = .75

```

Relationship of bias factor $K = R^*/R$, linkage probability $P_L$, and vaccination reporting probability $r_V$,
given $P(V) = `r pV`$, $R = `r R`$, and $N^* = N$.

```{r, fig.width=6, fig.height=4}
# fig.width=6, fig.height=4, dpi=300
# `pV*` = 0.5
f1 = function(pL, rV) 
{
  reporting_multiplier(
    
    `p(V)` = pV,
    R = R,
    `p(V*|V)` = rV,
    `p(L|V*E*)` = pL) %>% pull(`R*`)
  
}

rVs = (6:10)/10
rv_labels = paste("r_V =", formatC(rVs, format = "f", digits = 1 ))

plot1 = ggplot() +
  xlim(0.5,1.07) +
  
  expand_limits(y = 0) +
  geom_function(fun = function(x) f1(x, rV = 0.6), xlim = c(0.5,1)) +
  geom_function(fun = function(x) f1(x, rV = 0.7), xlim = c(0.5,1)) +
  geom_function(fun = function(x) f1(x, rV = 0.8), xlim = c(0.5,1)) +
  geom_function(fun = function(x) f1(x, rV = 0.9), xlim = c(0.5,1)) +
  geom_function(fun = function(x) f1(x, rV = 1.0), xlim = c(0.5,1)) +
  # geom_hline(yintercept = R, col = "black", linetype = 2) +
  geom_segment(aes(x = .5, xend = 1, y = R, yend = R), linetype = 2) + 
  annotate("text", 
            parse = TRUE,
           # fill = "white",
           label = latex2exp::TeX(rv_labels, output = "character"), x = 1.04, y = f1(1, rVs) + .001) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  # guides(col = NULL) + 
  xlab(latex2exp::TeX("p_L = Pr(Records Linked | Event and Vaccination Both Recorded)")) +
  ylab(latex2exp::TeX("R^* = Estimated Relative Risk (Vaccinated/Not)")) +
  
  labs(color = latex2exp::TeX("r_V")) + 
  scale_y_continuous(
    limits = c(0,0.4),
     sec.axis = sec_axis( trans=~ (1 - .) * 100, name="Estimated Vaccine Efficacy (%)")
  )

print(plot1)


```


## Table 1

```{r, include = FALSE}

pV = .75
rD = .9
rV = .9
N = 11 * 10^6
`N*` = N

all_results = gen_tab1(`p(V)` = pV, `p(E*|E)` = rD, `p(V*|V)` = rV, 
                       `N*` = `N*`,
                       `R` = c(1, .2),
                       `p(L|V*E*)` = c(.95, .9, .7))

```

Simulation results with $P(V) = `r pV`$, $r_D = `r rD`$, $r_V = `r rV`$, and $N^* = N = 11 * 10^6$:

```{r, results = 'asis'}

pander::pander(all_results)

```


## Table 2

```{r, include = FALSE}

pV = .75
rD = .7
rV = .9
N = 11 * 10^6
`N*` = N

all_results = gen_tab1(`p(V)` = pV, `p(E*|E)` = rD, `p(V*|V)` = rV, 
                       `N*` = `N*`,
                       `R` = c(1, .2),
                       `p(L|V*E*)` = c(.95, .9, .7))
```

Simulation results with $P(V) = `r pV`$, $r_D = `r rD`$, $r_V = `r rV`$, and $N^* = N = 11 * 10^6$:

```{r, results = 'asis'}
pander::pander(all_results)
```


## Table 3

```{r, include = FALSE}

pV = .75
rD = .9
rV = .9
R = .2
pL = .9
N = 11 * 10^6
multiplier = c(1.2, 1.1, 1.05, 1, .95, .9, .8)
`N*` = N * multiplier

all_results = gen_tab1(`p(V)` = pV, 
                       `p(E*|E)` = rD, 
                       `p(V*|V)` = rV, 
                       `N*` = `N*`,
                       `R` = R,
                       `p(L|V*E*)` = pL) %>%
  rename(`$N^*$` = `$N*$`) %>%
  mutate(`$N^*$` = scales::number(`$N^*$`, big.mark = ","))

all_results = bind_cols(
  "$N^*/N$" = multiplier,
  all_results
)

```

Simulation results for varying $N^*$ (with $P(V) = `r pV`$, $r_D = `r rD`$, $r_V = `r rV`$, $p_L = `r pL`$, and $R = `r R`$):

```{r, results = 'asis'}
pander(all_results)
```
